version: '3'

services:
  mongodb:
    image: mongo:4.2.3
    container_name: mongodb
    ports:
      - 27017:27017

  javalin_app:
    build: .
    container_name: javalin_app
    ports:
      - 7070:7070
    environment:
      MONGO_HOST: mongodb
    depends_on:
      mongodb:
        condition: service_started