name: Dev branch

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - name: Access to the code
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify